dataset = [
    # titoli di studio
    {"categoria": "titoli_di_studio", "testo": "Laurea in Ingegneria Informatica",
     "domanda": "Hai una laurea in Ingegneria Informatica?"},
    {"categoria": "titoli_di_studio", "testo": "Laurea in Giurisprudenza",
     "domanda": "Hai una laurea in Giurisprudenza?"},
    {"categoria": "titoli_di_studio", "testo": "Laurea in Ingegneria Civile",
     "domanda": "Hai una laurea in Ingegneria Civile?"},
    {"categoria": "titoli_di_studio", "testo": "Laurea in Medicina", "domanda": "Hai una laurea in Medicina?"},
    {"categoria": "titoli_di_studio", "testo": "Diploma di Scuola Superiore",
     "domanda": "Hai un diploma di Scuola Superiore?"},
    {"categoria": "titoli_di_studio", "testo": "Laurea in Economia Aziendale",
     "domanda": "Hai una laurea in Economia Aziendale?"},
    {"categoria": "titoli_di_studio", "testo": "Laurea in Architettura", "domanda": "Hai una laurea in Architettura?"},
    {"categoria": "titoli_di_studio", "testo": "Diploma di Tecnico Informatico",
     "domanda": "Hai un diploma di Tecnico Informatico?"},
    {"categoria": "titoli_di_studio", "testo": "Laurea in Scienze Politiche",
     "domanda": "Hai una laurea in Scienze Politiche?"},
    {"categoria": "titoli_di_studio", "testo": "Diploma in Design Industriale",
     "domanda": "Hai un diploma in Design Industriale?"},
    {"categoria": "titoli_di_studio", "testo": "Laurea in Psicologia", "domanda": "Hai una laurea in Psicologia?"},
    {"categoria": "titoli_di_studio", "testo": "Diploma in Grafica Pubblicitaria",
     "domanda": "Hai un diploma in Grafica Pubblicitaria?"},
    {"categoria": "titoli_di_studio", "testo": "Laurea in Lettere Moderne",
     "domanda": "Hai una laurea in Lettere Moderne?"},
    {"categoria": "titoli_di_studio", "testo": "Diploma in Elettronica Industriale",
     "domanda": "Hai un diploma in Elettronica Industriale?"},
    {"categoria": "titoli_di_studio", "testo": "Laurea in Scienze dell'Educazione",
     "domanda": "Hai una laurea in Scienze dell'Educazione?"},
    {"categoria": "titoli_di_studio", "testo": "Diploma in Lingue Straniere",
     "domanda": "Hai un diploma in Lingue Straniere?"},
    {"categoria": "titoli_di_studio", "testo": "Laurea in Fisica", "domanda": "Hai una laurea in Fisica?"},
    {"categoria": "titoli_di_studio", "testo": "Diploma in Meccanica", "domanda": "Hai un diploma in Meccanica?"},
    {"categoria": "titoli_di_studio", "testo": "Laurea in Scienze della Comunicazione",
     "domanda": "Hai una laurea in Scienze della Comunicazione?"},
    {"categoria": "titoli_di_studio", "testo": "Diploma in Turismo", "domanda": "Hai un diploma in Turismo?"},
    {"categoria": "titoli_di_studio", "testo": "Laurea in Ingegneria Elettronica",
     "domanda": "Hai una laurea in Ingegneria Elettronica?"},
    {"categoria": "titoli_di_studio", "testo": "Diploma in Commercio Estero",
     "domanda": "Hai un diploma in Commercio Estero?"},
    {"categoria": "titoli_di_studio", "testo": "Laurea in Chimica", "domanda": "Hai una laurea in Chimica?"},
    {"categoria": "titoli_di_studio", "testo": "Diploma in Pasticceria", "domanda": "Hai un diploma in Pasticceria?"},
    {"categoria": "titoli_di_studio", "testo": "Laurea in Scienze Motorie",
     "domanda": "Hai una laurea in Scienze Motorie?"},
    {"categoria": "titoli_di_studio", "testo": "Diploma in Arti Applicate",
     "domanda": "Hai un diploma in Arti Applicate?"},
    {"categoria": "titoli_di_studio", "testo": "Laurea in Storia dell'Arte",
     "domanda": "Hai una laurea in Storia dell'Arte?"},
    {"categoria": "titoli_di_studio", "testo": "Diploma in Modellismo Industriale",
     "domanda": "Hai un diploma in Modellismo Industriale?"},
    {"categoria": "titoli_di_studio", "testo": "Laurea in Scienze della Formazione",
     "domanda": "Hai una laurea in Scienze della Formazione?"},
    {"categoria": "titoli_di_studio", "testo": "Diploma in Fotografia", "domanda": "Hai un diploma in Fotografia?"},
    {"categoria": "titoli_di_studio", "testo": "Laurea in Filosofia", "domanda": "Hai una laurea in Filosofia?"},
    {"categoria": "titoli_di_studio", "testo": "Diploma in Arte e Design",
     "domanda": "Hai un diploma in Arte e Design?"},
    {"categoria": "titoli_di_studio", "testo": "Laurea Triennale",
     "domanda": "Hai almeno una laurea triennale nell'ambito?"},
    {"categoria": "titoli_di_studio", "testo": "Diploma in Restauro e Conservazione dei Beni Culturali",
     "domanda": "Hai un diploma in Restauro e Conservazione dei Beni Culturali?"},
    {"categoria": "titoli_di_studio", "testo": "Laurea in Scienze dell'Alimentazione",
     "domanda": "Hai una laurea in Scienze dell'Alimentazione?"},
    {"categoria": "titoli_di_studio", "testo": "Diploma in Design di Interni",
     "domanda": "Hai un diploma in Design di Interni?"},
    {"categoria": "titoli_di_studio", "testo": "Laurea in Agraria", "domanda": "Hai una laurea in Agraria?"},
    {"categoria": "titoli_di_studio", "testo": "Diploma in Estetica", "domanda": "Hai un diploma in Estetica?"},
    {"categoria": "titoli_di_studio", "testo": "Laurea in Scienze Motorie e Sportive",
     "domanda": "Hai una laurea in Scienze Motorie e Sportive?"},
    {"categoria": "titoli_di_studio", "testo": "Diploma in Grafica e Comunicazione",
     "domanda": "Hai un diploma in Grafica e Comunicazione?"},
    {"categoria": "titoli_di_studio", "testo": "Laurea in Musicologia", "domanda": "Hai una laurea in Musicologia?"},
    {"categoria": "titoli_di_studio", "testo": "Diploma in Ottica", "domanda": "Hai un diploma in Ottica?"},
    {"categoria": "titoli_di_studio", "testo": "Laurea in Geologia", "domanda": "Hai una laurea in Geologia?"},
    {"categoria": "titoli_di_studio", "testo": "Diploma in Sartoria", "domanda": "Hai un diploma in Sartoria?"},
    {"categoria": "titoli_di_studio", "testo": "Laurea in Scienze Ambientali",
     "domanda": "Hai una laurea in Scienze Ambientali?"},
    {"categoria": "titoli_di_studio", "testo": "Diploma in Falegnameria", "domanda": "Hai un diploma in Falegnameria?"},
    {"categoria": "titoli_di_studio", "testo": "Laurea in Antropologia", "domanda": "Hai una laurea in Antropologia?"},
    {"categoria": "titoli_di_studio", "testo": "Diploma in Elettronica", "domanda": "Hai un diploma in Elettronica?"},

    {"categoria": "competenze", "testo": "gestione di progetti open-source",
     "domanda": "Hai competenze nella gestione di progetti open-source?"},
    {"categoria": "competenze", "testo": "Progettazione, sviluppo e manutenzione di applicazioni software",
     "domanda": "Hai competenze nella progettazione di applicazioni software?"},
    {"categoria": "competenze", "testo": "test",
     "domanda": "Sei capace di effettuare test?"},
    {"categoria": "competenze", "testo": "debug",
     "domanda": "Sei capace di fare debug?"},
    {"categoria": "competenze", "testo": "ottimizzazione del codice",
     "domanda": "Sei capace di fare ottimizzazione del codice?"},
    {"categoria": "competenze", "testo": "Creare documentazione tecnica dettagliata",
     "domanda": "Sai creare documentazione tecnica dettagliata?"},
    {"categoria": "competenze", "testo": "Conoscenza approfondita delle librerie standard di C",
     "domanda": "Hai una conoscenza approfondita delle librerie standard di C?"},
    {"categoria": "competenze", "testo": "Linux",
     "domanda": "Hai competenze per Linux?"},
    {"categoria": "competenze", "testo": "librerie standard di C",
     "domanda": "Conosci le librerie standard di C?"},
    {"categoria": "competenze", "testo": "best practice di programmazione",
     "domanda": "Conosci la best practice di programmazione?"},
    {"categoria": "competenze", "testo": "problem-solving",
     "domanda": "Hai capacità di problem-solving?"},
    {"categoria": "competenze", "testo": "debugging",
     "domanda": "Hai competenze nel debugging?"},
    {"categoria": "competenze", "testo": "C",
     "domanda": "Sai programmare in C?"},
    {"categoria": "competenze", "testo": "Shell scripting",
     "domanda": "Hai competenze in Shell scripting?"},
    {"categoria": "competenze", "testo": "Python",
     "domanda": "Sai programmare in Python?"},
    {"categoria": "competenze", "testo": "Mysql",
     "domanda": "Sai utilizzare Mysql?"},
    {"categoria": "competenze", "testo": "SqlServer",
     "domanda": "Sai utilizzare SqlServer?"},
    {"categoria": "competenze", "testo": "versioning software",
     "domanda": "Hai competenze nel versioning software?"},
    {"categoria": "competenze", "testo": "Git",
     "domanda": "Hai mai utilizzato Git?"},
    {"categoria": "competenze", "testo": "Java",
     "domanda": "Sai programmare in Java?"},
    {"categoria": "competenze", "testo": "Progettazione di database",
     "domanda": "Hai competenze nella progettazione di database?"},
    {"categoria": "competenze", "testo": "Analisi dei dati", "domanda": "Hai competenze nell'analisi dei dati?"},
    {"categoria": "competenze", "testo": "Sviluppo di applicazioni mobile",
     "domanda": "Hai competenze nello sviluppo di applicazioni mobile?"},
    {"categoria": "competenze", "testo": "Gestione di reti informatiche",
     "domanda": "Hai competenze nella gestione di reti informatiche?"},
    {"categoria": "competenze", "testo": "Programmazione in Java", "domanda": "Sai programmare in Java?"},
    {"categoria": "competenze", "testo": "Utilizzo di framework JavaScript",
     "domanda": "Hai competenze nell'utilizzo di framework JavaScript?"},
    {"categoria": "competenze", "testo": "Gestione di progetti IT",
     "domanda": "Hai competenze nella gestione di progetti IT?"},
    {"categoria": "competenze", "testo": "Conoscenza di metodologie Agile", "domanda": "Conosci le metodologie Agile?"},
    {"categoria": "competenze", "testo": "Sviluppo di siti web responsive",
     "domanda": "Hai competenze nello sviluppo di siti web responsive?"},
    {"categoria": "competenze", "testo": "Utilizzo di sistemi di versioning come Git",
     "domanda": "Hai competenze nell'utilizzo di sistemi di versioning come Git?"},
    {"categoria": "competenze", "testo": "Creazione e gestione di database SQL",
     "domanda": "Sai creare e gestire database SQL?"},
    {"categoria": "competenze", "testo": "Conoscenza di linguaggi di scripting come Python",
     "domanda": "Conosci linguaggi di scripting come Python?"},
    {"categoria": "competenze", "testo": "Utilizzo di strumenti di analisi statistica",
     "domanda": "Hai competenze nell'utilizzo di strumenti di analisi statistica?"},
    {"categoria": "competenze", "testo": "Gestione di server web",
     "domanda": "Hai competenze nella gestione di server web?"},
    {"categoria": "competenze", "testo": "Sviluppo di applicazioni desktop",
     "domanda": "Hai competenze nello sviluppo di applicazioni desktop?"},
    {"categoria": "competenze", "testo": "Implementazione di algoritmi di machine learning",
     "domanda": "Hai competenze nell'implementazione di algoritmi di machine learning?"},
    {"categoria": "competenze", "testo": "Gestione di sistemi operativi Linux",
     "domanda": "Hai competenze nella gestione di sistemi operativi Linux?"},
    {"categoria": "competenze", "testo": "Sviluppo di interfacce utente intuitive",
     "domanda": "Hai competenze nello sviluppo di interfacce utente intuitive?"},
    {"categoria": "competenze", "testo": "Risoluzione di problemi hardware",
     "domanda": "Hai competenze nella risoluzione di problemi hardware?"},
    {"categoria": "competenze", "testo": "visualizzazione dati",
     "domanda": "Hai competenze nell'utilizzo di strumenti di visualizzazione dati?"},
    {"categoria": "competenze", "testo": "Gestione di piattaforme di cloud computing",
     "domanda": "Hai competenze nella gestione di piattaforme di cloud computing?"},
    {"categoria": "competenze", "testo": "Codesys 3?", "domanda": "Hai esperienza con Codesys 3?"},
    {"categoria": "competenze", "testo": "Bosch Rexroth?",
     "domanda": "Hai lavorato con Bosch Rexroth?"},
    {"categoria": "competenze", "testo": "manutenzione e aggiornamento del software?",
     "domanda": "Hai esperienza nella manutenzione e nell'aggiornamento del software?"},
    {"categoria": "competenze", "testo": "Motion?",
     "domanda": "Hai competenze in Motion?"},
    {"categoria": "competenze", "testo": "Panel PLC Eaton?",
     "domanda": "Hai mai utilizzato i Panel PLC Eaton?"},
    {"categoria": "competenze", "testo": "Omron?", "domanda": "Hai mai lavorato con Omron?"},
    {"categoria": "competenze", "testo": "sviluppo del software?",
     "domanda": "Hai esperienza nello sviluppo del software?"},
    {"categoria": "competenze", "testo": "Codesys 2?", "domanda": "Hai esperienza con Codesys 2?"},
    {"categoria": "competenze", "testo": "HMI?",
     "domanda": "Hai esperienza nell'utilizzo degli HMI?"},
    {"categoria": "competenze", "testo": "Hai lavorato con Eaton?", "domanda": "Eaton?"},
    {"categoria": "competenze", "testo": "Safety PLC?",
     "domanda": "Hai esperienza con i Safety PLC?"},
    {"categoria": "competenze",
     "testo": "integrazione di sistemi robotici e sistemi di controllo della qualità?",
     "domanda": "Hai esperienza nell'integrazione di sistemi robotici e sistemi di controllo della qualità?"},
    {"categoria": "competenze", "testo": "PLC Omron?", "domanda": "Hai mai utilizzato PLC Omron?"},
    {"categoria": "competenze", "testo": "Weintek?",
     "domanda": "Hai esperienza con i prodotti Weintek?"},
    {"categoria": "competenze", "testo": "Bootstrap", "domanda": "Conosci Bootstrap?"},
    {"categoria": "competenze", "testo": "SASS", "domanda": "Hai utilizzato SASS?"},
    {"categoria": "competenze", "testo": "LESS", "domanda": "Sei familiare con LESS?"},
    {"categoria": "competenze", "testo": "Vue.js", "domanda": "Hai lavorato con Vue.js?"},
    {"categoria": "competenze", "testo": "TypeScript", "domanda": "Conosci TypeScript?"},
    {"categoria": "competenze", "testo": "Redux", "domanda": "Hai esperienza con Redux?"},
    {"categoria": "competenze", "testo": "GraphQL", "domanda": "Conosci GraphQL?"},
    {"categoria": "competenze", "testo": "Firebase", "domanda": "Hai utilizzato Firebase?"},
    {"categoria": "competenze", "testo": "Jira", "domanda": "Hai mai utilizzato Jira?"},
    {"categoria": "competenze", "testo": "Scrum", "domanda": "Hai mai lavorato con Scrum?"},
    {"categoria": "competenze", "testo": "Kanban", "domanda": "Hai competenze con  Kanban?"},
    {"categoria": "competenze", "testo": "Machine Learning", "domanda": "Hai competenze in Machine Learning?"},
    {"categoria": "competenze", "testo": "Natural Language Processing",
     "domanda": "Hai competenze in Natural Language Processing?"},
    {"categoria": "competenze", "testo": "Computer Vision", "domanda": "Hai lavorato con Computer Vision?"},
    {"categoria": "competenze", "testo": "Blockchain", "domanda": "Conosci le basi della Blockchain?"},
    {"categoria": "competenze", "testo": "Cybersecurity", "domanda": "Hai competenze in Cybersecurity?"},
    {"categoria": "competenze", "testo": "Data Visualization",
     "domanda": "Hai esperienza nella visualizzazione dei dati?"},
    {"categoria": "competenze", "testo": "UI/UX Design", "domanda": "Hai esperienza nell'UI/UX Design?"},
    {"categoria": "competenze", "testo": "Angular", "domanda": "Hai esperienza con Angular?"},
    {"categoria": "competenze", "testo": "React Native",
     "domanda": "Hai mai utilizzato React Nativee?"},
    {"categoria": "competenze", "testo": "Flutter", "domanda": "Hai competenze in Flutter?"},
    {"categoria": "competenze", "testo": "Django", "domanda": "Hai mai lavorato con Django?"},
    {"categoria": "competenze", "testo": "Flask", "domanda": "Hai esperienza con Flask?"},
    {"categoria": "competenze", "testo": "Node.js", "domanda": "Hai competenze in Node.js?"},
    {"categoria": "competenze", "testo": "Express.js", "domanda": "Hai competenze in Express.jsb?"},
    {"categoria": "competenze", "testo": "MongoDB",
     "domanda": "Hai esperienza con MongoDB?"},
    {"categoria": "competenze", "testo": "MySQL",
     "domanda": "Hai competenze in MySQL?"},
    {"categoria": "competenze", "testo": "PostgreSQL",
     "domanda": "Hai esperienza con PostgreSQL?"},
    {"categoria": "competenze", "testo": "Serverless", "domanda": "Hai mai utilizzato architetture serverless?"},
    {"categoria": "competenze", "testo": "AWS", "domanda": "Hai esperienza con i servizi AWS (Amazon Web Services)?"},
    {"categoria": "competenze", "testo": "Azure", "domanda": "Conosci i servizi di Azure?"},
    {"categoria": "competenze", "testo": "Docker",
     "domanda": "Hai mai lavorato con Docker?"},
    {"categoria": "competenze", "testo": "pacchetto Office",
     "domanda": "Hai mai lavorato con il pacchetto Office?"},
    {"categoria": "competenze", "testo": "Vue.js", "domanda": "Conosci Vue.js?"},
    {"categoria": "competenze", "testo": "Angular", "domanda": "Hai competenze in Angular?"},
    {"categoria": "competenze", "testo": "PHP", "domanda": "Sai programmare in PHP?"},
    {"categoria": "competenze", "testo": "Node.js", "domanda": "Conosci Node.js?"},
    {"categoria": "competenze", "testo": "Express.js", "domanda": "Hai esperienza con Express.js?"},
    {"categoria": "competenze", "testo": "MongoDB", "domanda": "Sai utilizzare MongoDB?"},
    {"categoria": "competenze", "testo": "Docker", "domanda": "Hai competenze con Docker?"},
    {"categoria": "competenze", "testo": "Kubernetes", "domanda": "Conosci Kubernetes?"},
    {"categoria": "competenze", "testo": "AWS", "domanda": "Hai esperienza con AWS?"},
    {"categoria": "competenze", "testo": "Azure", "domanda": "Sai utilizzare Azure?"},
    {"categoria": "competenze", "testo": "Firebase", "domanda": "Conosci Firebase?"},
    {"categoria": "competenze", "testo": "RESTful APIs", "domanda": "Hai esperienza nella creazione di RESTful APIs?"},
    {"categoria": "competenze", "testo": "GraphQL", "domanda": "Conosci GraphQL?"},
    {"categoria": "competenze", "testo": "Microservices", "domanda": "Hai competenze nel design di Microservices?"},
    {"categoria": "competenze", "testo": "Blockchain", "domanda": "Hai esperienza con la Blockchain?"},
    {"categoria": "competenze", "testo": "Data Structures", "domanda": "Conosci le strutture dati?"},
    {"categoria": "competenze", "testo": "Algorithms", "domanda": "Hai conoscenze sugli algoritmi?"},
    {"categoria": "competenze", "testo": "Machine Learning", "domanda": "Sai applicare tecniche di Machine Learning?"},
    {"categoria": "competenze", "testo": "Deep Learning", "domanda": "Conosci Deep Learning?"},
    {"categoria": "competenze", "testo": "Natural Language Processing (NLP)",
     "domanda": "Hai competenze in Natural Language Processing?"},
    {"categoria": "competenze", "testo": "Computer Vision", "domanda": "Sai lavorare con Computer Vision?"},
    {"categoria": "competenze", "testo": "Big Data", "domanda": "Hai esperienza in Big Data?"},
    {"categoria": "competenze", "testo": "Hadoop", "domanda": "Conosci Hadoop?"},
    {"categoria": "competenze", "testo": "Spark", "domanda": "Sai utilizzare Apache Spark?"},
    {"categoria": "competenze", "testo": "SQL", "domanda": "Conosci SQL?"},
    {"categoria": "competenze", "testo": "NoSQL", "domanda": "Hai competenze in database NoSQL?"},
    {"categoria": "competenze", "testo": "Scrum", "domanda": "Conosci la metodologia Scrum?"},
    {"categoria": "competenze", "testo": "Agile", "domanda": "Hai esperienza con lo sviluppo Agile?"},
    {"categoria": "competenze", "testo": "CI/CD",
     "domanda": "Conosci CI/CD (Continuous Integration/Continuous Deployment)?"},
    {"categoria": "competenze", "testo": "Jenkins", "domanda": "Hai esperienza con Jenkins?"},
    {"categoria": "competenze", "testo": "DevOps", "domanda": "Sai praticare DevOps?"},
    {"categoria": "competenze", "testo": "GitLab", "domanda": "Conosci GitLab?"},
    {"categoria": "competenze", "testo": "Bitbucket", "domanda": "Hai esperienza con Bitbucket?"},
    {"categoria": "competenze", "testo": "JIRA", "domanda": "Conosci JIRA?"},
    {"categoria": "competenze", "testo": "Confluence", "domanda": "Hai competenze in Confluence?"},
    {"categoria": "competenze", "testo": "Unit Testing", "domanda": "Sai fare Unit Testing?"},
    {"categoria": "competenze", "testo": "Integration Testing", "domanda": "Hai competenze in Integration Testing?"},
    {"categoria": "competenze", "testo": "Test Automation", "domanda": "Conosci l'automazione dei test?"},
    {"categoria": "competenze", "testo": "Security", "domanda": "Hai competenze in sicurezza informatica?"},
    {"categoria": "competenze", "testo": "Networking", "domanda": "Hai competenze in Networking?"},
    {"categoria": "competenze", "testo": "Protocolli di rete", "domanda": "Conosci i protocolli di rete?"},
    {"categoria": "competenze", "testo": "Routing e switching", "domanda": "Hai competenze in Routing e Switching?"},
    {"categoria": "competenze", "testo": "Configurazione di reti LAN/WAN", "domanda": "Sai configurare reti LAN/WAN?"},
    {"categoria": "competenze", "testo": "Firewalls e sicurezza di rete",
     "domanda": "Hai competenze sui Firewalls e sulla sicurezza di rete?"},
    {"categoria": "competenze", "testo": "Virtualizzazione", "domanda": "Conosci la virtualizzazione?"},
    {"categoria": "competenze", "testo": "Sistemi operativi Windows",
     "domanda": "Hai competenze sui sistemi operativi Windows?"},
    {"categoria": "competenze", "testo": "Sistemi operativi Unix/Linux",
     "domanda": "Conosci i sistemi operativi Unix/Linux?"},
    {"categoria": "competenze", "testo": "Amministrazione di sistemi operativi",
     "domanda": "Hai esperienza nell'amministrazione di sistemi operativi?"},
    {"categoria": "competenze", "testo": "Automazione di processi", "domanda": "Sai automatizzare processi?"},
    {"categoria": "competenze", "testo": "Controllo e automazione industriale",
     "domanda": "Hai competenze nel controllo e nell'automazione industriale?"},
    {"categoria": "competenze", "testo": "Robotica", "domanda": "Conosci la robotica?"},
    {"categoria": "competenze", "testo": "Sistemi SCADA", "domanda": "Hai esperienza con i sistemi SCADA?"},
    {"categoria": "competenze", "testo": "PLC Programming", "domanda": "Hai competenze nella programmazione PLC?"},
    {"categoria": "competenze", "testo": "Automazione di processi industriali",
     "domanda": "Sai automatizzare processi industriali?"},
    {"categoria": "competenze", "testo": "Sistemi Embedded", "domanda": "Hai competenze nei sistemi Embedded?"},
    {"categoria": "competenze", "testo": "Controllo di processo", "domanda": "Conosci il controllo di processo?"},
    {"categoria": "competenze", "testo": "Modellazione e simulazione di sistemi",
     "domanda": "Hai esperienza nella modellazione e simulazione di sistemi?"},
    {"categoria": "competenze", "testo": "Automazione dei test",
     "domanda": "Hai competenze nell'automazione dei test?"},
    {"categoria": "competenze", "testo": "Analisi dei requisiti", "domanda": "Sai fare analisi dei requisiti?"},
    {"categoria": "competenze", "testo": "Controllo di qualità", "domanda": "Hai competenze nel controllo di qualità?"},
    {"categoria": "competenze", "testo": "Gestione di risorse informatiche",
     "domanda": "Hai esperienza nella gestione di risorse informatiche?"},
    {"categoria": "competenze", "testo": "Sistemi di gestione di database",
     "domanda": "Conosci i sistemi di gestione di database?"},
    {"categoria": "competenze", "testo": "Sicurezza informatica",
     "domanda": "Hai competenze in sicurezza informatica?"},
    {"categoria": "competenze", "testo": "Analisi dei dati", "domanda": "Sai fare analisi dei dati?"},
    {"categoria": "competenze", "testo": "Risposta agli incidenti informatici",
     "domanda": "Hai esperienza nella risposta agli incidenti informatici?"},
    {"categoria": "competenze", "testo": "Privacy e conformità", "domanda": "Hai competenze in privacy e conformità?"},
    {"categoria": "competenze", "testo": "Gestione della configurazione", "domanda": "Sai gestire la configurazione?"},
    {"categoria": "competenze", "testo": "Programmazione di microcontrollori",
     "domanda": "Hai competenze nella programmazione di microcontrollori?"},
    {"categoria": "competenze", "testo": "Intelligenza Artificiale",
     "domanda": "Hai competenze in Intelligenza Artificiale?"},
    {"categoria": "competenze", "testo": "Apprendimento automatico", "domanda": "Conosci l'apprendimento automatico?"},
    {"categoria": "competenze", "testo": "Reti neurali", "domanda": "Hai competenze nelle reti neurali?"},
    {"categoria": "competenze", "testo": "Deep Reinforcement Learning",
     "domanda": "Conosci il Deep Reinforcement Learning?"},
    {"categoria": "competenze", "testo": "Regressione", "domanda": "Sai fare regressione?"},
    {"categoria": "competenze", "testo": "Classificazione", "domanda": "Hai competenze nella classificazione?"},
    {"categoria": "competenze", "testo": "Clusterizzazione", "domanda": "Conosci la clusterizzazione?"},
    {"categoria": "competenze", "testo": "Elaborazione del linguaggio naturale",
     "domanda": "Hai competenze nell'elaborazione del linguaggio naturale?"},
    {"categoria": "competenze", "testo": "Visione artificiale", "domanda": "Conosci la visione artificiale?"},
    {"categoria": "competenze", "testo": "Robotica avanzata", "domanda": "Hai competenze in robotica avanzata?"},
    {"categoria": "competenze", "testo": "Automazione dei processi cognitivi",
     "domanda": "Sai automatizzare processi cognitivi?"},
    {"categoria": "competenze", "testo": "Ottimizzazione dei modelli di Machine Learning",
     "domanda": "Conosci l'ottimizzazione dei modelli di Machine Learning?"},
    {"categoria": "competenze", "testo": "Interpretazione dei modelli di Machine Learning",
     "domanda": "Hai esperienza nell'interpretazione dei modelli di Machine Learning?"},
    {"categoria": "competenze", "testo": "Riduzione della dimensionalità",
     "domanda": "Sai ridurre la dimensionalità dei dati?"},
    {"categoria": "competenze", "testo": "Analisi delle prestazioni dei modelli di Machine Learning",
     "domanda": "Hai competenze nell'analisi delle prestazioni dei modelli di Machine Learning?"},
    {"categoria": "competenze", "testo": "Computer Vision 3D", "domanda": "Hai esperienza in Computer Vision 3D?"},
    {"categoria": "competenze", "testo": "Preprocessing dei dati", "domanda": "Sai fare preprocessing dei dati?"},
    {"categoria": "competenze", "testo": "Estrazione delle caratteristiche",
     "domanda": "Conosci l'estrazione delle caratteristiche?"},
    {"categoria": "competenze", "testo": "Analisi di serie temporali",
     "domanda": "Hai esperienza nell'analisi di serie temporali?"},
    {"categoria": "competenze", "testo": "Rete Generativa Avversaria (GAN)",
     "domanda": "Conosci le Reti Generative Avversarie (GAN)?"},
    {"categoria": "competenze", "testo": "Distributed Computing",
     "domanda": "Hai competenze nel Distributed Computing?"},
    {"categoria": "competenze", "testo": "Calcolo parallelo", "domanda": "Sai fare calcolo parallelo?"},
    {"categoria": "competenze", "testo": "Algoritmi genetici", "domanda": "Conosci gli algoritmi genetici?"},
    {"categoria": "competenze", "testo": "Sistemi multi-agente", "domanda": "Hai esperienza nei sistemi multi-agente?"},
    {"categoria": "competenze", "testo": "Teoria dei giochi", "domanda": "Conosci la teoria dei giochi?"},
    {"categoria": "competenze", "testo": "Ricerca operativa", "domanda": "Hai competenze nella ricerca operativa?"},
    {"categoria": "competenze", "testo": "Ottimizzazione combinatoria",
     "domanda": "Sai fare ottimizzazione combinatoria?"},
    {"categoria": "competenze", "testo": "Analisi numerica", "domanda": "Conosci l'analisi numerica?"},
    {"categoria": "competenze", "testo": "Teoria dell'informazione",
     "domanda": "Hai competenze nella teoria dell'informazione?"},
    {"categoria": "competenze", "testo": "Analisi delle reti sociali",
     "domanda": "Conosci l'analisi delle reti sociali?"},
    {"categoria": "competenze", "testo": "Simulazione al computer",
     "domanda": "Hai esperienza nella simulazione al computer?"},
    {"categoria": "competenze", "testo": "Riconoscimento dei pattern",
     "domanda": "Sai fare riconoscimento dei pattern?"},
    {"categoria": "competenze", "testo": "Apprendimento federato",
     "domanda": "Hai competenze nell'apprendimento federato?"},
    {"categoria": "competenze", "testo": "Reti Bayesiane", "domanda": "Conosci le reti Bayesiane?"},
    {"categoria": "competenze", "testo": "Statistica bayesiana",
     "domanda": "Hai competenze nella statistica bayesiana?"},
    {"categoria": "competenze", "testo": "Metodi Monte Carlo", "domanda": "Conosci i metodi Monte Carlo?"},
    {"categoria": "competenze", "testo": "Analisi del testo", "domanda": "Hai esperienza nell'analisi del testo?"},
    {"categoria": "competenze", "testo": "Fusioni di dati", "domanda": "Sai fare fusioni di dati?"},
    {"categoria": "competenze", "testo": "Scienza dei dati", "domanda": "Hai competenze nella scienza dei dati?"},
    {"categoria": "competenze", "testo": "Interpolazione e approssimazione",
     "domanda": "Conosci l'interpolazione e l'approssimazione?"},
    {"categoria": "competenze", "testo": "Algoritmi di ricerca",
     "domanda": "Hai competenze negli algoritmi di ricerca?"},
    {"categoria": "competenze", "testo": "Intelligenza artificiale etica",
     "domanda": "Conosci l'intelligenza artificiale etica?"},
    {"categoria": "competenze", "testo": "Sistemi esperti", "domanda": "Hai esperienza nei sistemi esperti?"},
    {"categoria": "competenze", "testo": "Predizione e analisi delle serie storiche",
     "domanda": "Sai fare predizione e analisi delle serie storiche?"},
    {"categoria": "competenze", "testo": "Analisi di sentimenti", "domanda": "Conosci l'analisi di sentimenti?"},
    {"categoria": "competenze", "testo": "Analisi delle immagini mediche",
     "domanda": "Hai esperienza nell'analisi delle immagini mediche?"},
    {"categoria": "competenze", "testo": "Sviluppo di applicazioni web",
     "domanda": "Hai competenze nello sviluppo di applicazioni web?"},
    {"categoria": "competenze", "testo": "Test-driven development (TDD)",
     "domanda": "Conosci il test-driven development (TDD)?"},
    {"categoria": "competenze", "testo": "Behavior-driven development (BDD)",
     "domanda": "Hai esperienza nel behavior-driven development (BDD)?"},
    {"categoria": "competenze", "testo": "Programmazione orientata agli oggetti",
     "domanda": "Sai programmare in modo orientato agli oggetti?"},
    {"categoria": "competenze", "testo": "Programmazione funzionale",
     "domanda": "Hai competenze nella programmazione funzionale?"},
    {"categoria": "competenze", "testo": "Progettazione di interfacce utente",
     "domanda": "Sai progettare interfacce utente?"},
    {"categoria": "competenze", "testo": "Progettazione di basi di dati",
     "domanda": "Hai competenze nella progettazione di basi di dati?"},
    {"categoria": "competenze", "testo": "Integrazione di sistemi", "domanda": "Sai integrare sistemi?"},
    {"categoria": "competenze", "testo": "Manutenzione del software",
     "domanda": "Hai esperienza nella manutenzione del software?"},
    {"categoria": "competenze", "testo": "Analisi dei requisiti software",
     "domanda": "Sai fare analisi dei requisiti software?"},
    {"categoria": "competenze", "testo": "Gestione dei progetti software",
     "domanda": "Hai competenze nella gestione dei progetti software?"},
    {"categoria": "competenze", "testo": "Implementazione di algoritmi",
     "domanda": "Hai esperienza nell'implementazione di algoritmi?"},
    {"categoria": "competenze", "testo": "Manutenzione di siti web", "domanda": "Sai fare manutenzione di siti web?"},
    {"categoria": "competenze", "testo": "Creazione di applicazioni mobili",
     "domanda": "Hai competenze nella creazione di applicazioni mobili?"},
    {"categoria": "competenze", "testo": "Testing e debug di software",
     "domanda": "Hai esperienza nel testing e debug di software?"},
    {"categoria": "competenze", "testo": "Gestione dei dati", "domanda": "Hai competenze nella gestione dei dati?"},
    {"categoria": "competenze", "testo": "Sviluppo di algoritmi di ottimizzazione",
     "domanda": "Sai sviluppare algoritmi di ottimizzazione?"},
    {"categoria": "competenze", "testo": "Automazione dei processi di business",
     "domanda": "Hai competenze nell'automazione dei processi di business?"},
    {"categoria": "competenze", "testo": "Integrazione di servizi web", "domanda": "Sai integrare servizi web?"},
    {"categoria": "competenze", "testo": "Sviluppo di giochi", "domanda": "Hai esperienza nello sviluppo di giochi?"},
    {"categoria": "competenze", "testo": "Analisi delle prestazioni", "domanda": "Sai fare analisi delle prestazioni?"},
    {"categoria": "competenze", "testo": "Risorse umane e tecnologie dell'informazione",
     "domanda": "Hai competenze in risorse umane e tecnologie dell'informazione?"},
    {"categoria": "competenze", "testo": "Sistemi di gestione di contenuti",
     "domanda": "Conosci i sistemi di gestione di contenuti?"},
    {"categoria": "competenze", "testo": "Sviluppo di software embedded",
     "domanda": "Hai esperienza nello sviluppo di software embedded?"},
    {"categoria": "competenze", "testo": "Programmazione di microservizi", "domanda": "Sai programmare microservizi?"},
    {"categoria": "competenze", "testo": "Gestione delle infrastrutture IT",
     "domanda": "Hai competenze nella gestione delle infrastrutture IT?"},
    {"categoria": "competenze", "testo": "Sistemi di business intelligence",
     "domanda": "Conosci i sistemi di business intelligence?"},
    {"categoria": "competenze", "testo": "Sviluppo di software di automazione industriale",
     "domanda": "Hai esperienza nello sviluppo di software di automazione industriale?"},
    {"categoria": "competenze", "testo": "Analisi e progettazione di algoritmi",
     "domanda": "Sai analizzare e progettare algoritmi?"},
    {"categoria": "competenze", "testo": "Manutenzione e miglioramento dei processi IT",
     "domanda": "Hai competenze nella manutenzione e miglioramento dei processi IT?"},
    {"categoria": "competenze", "testo": "Sicurezza informatica",
     "domanda": "Hai competenze nella sicurezza informatica?"},
    {"categoria": "competenze", "testo": "Valutazione e gestione dei rischi IT",
     "domanda": "Sai valutare e gestire i rischi IT?"},
    {"categoria": "competenze", "testo": "Sviluppo di software per sistemi embedded",
     "domanda": "Hai esperienza nello sviluppo di software per sistemi embedded?"},
    {"categoria": "competenze", "testo": "Integrazione dei sistemi di automazione industriale",
     "domanda": "Sai integrare i sistemi di automazione industriale?"},
    {"categoria": "competenze", "testo": "Sviluppo di algoritmi di ottimizzazione",
     "domanda": "Conosci gli algoritmi di ottimizzazione?"},
    {"categoria": "competenze", "testo": "Analisi delle performance dei software",
     "domanda": "Hai esperienza nell'analisi delle performance dei software?"},
    {"categoria": "competenze", "testo": "Analisi e progettazione di database",
     "domanda": "Sai analizzare e progettare database?"},
    {"categoria": "competenze", "testo": "Sviluppo di applicazioni web responsive",
     "domanda": "Hai esperienza nello sviluppo di applicazioni web responsive?"},
    {"categoria": "competenze", "testo": "Automazione dei test di software",
     "domanda": "Sai automatizzare i test di software?"},
    {"categoria": "competenze", "testo": "Gestione di reti informatiche",
     "domanda": "Hai competenze nella gestione di reti informatiche?"},
    {"categoria": "competenze", "testo": "Ricerca e sviluppo di nuove tecnologie",
     "domanda": "Hai esperienza nella ricerca e sviluppo di nuove tecnologie?"},
    {"categoria": "competenze", "testo": "Sviluppo di applicazioni per dispositivi mobili",
     "domanda": "Sai sviluppare applicazioni per dispositivi mobili?"},
    {"categoria": "competenze", "testo": "Gestione di progetti IT",
     "domanda": "Hai esperienza nella gestione di progetti IT?"},
    {"categoria": "competenze", "testo": "Conoscenza dei protocolli di rete",
     "domanda": "Conosci i protocolli di rete?"},
    {"categoria": "competenze", "testo": "Sviluppo di applicazioni per dispositivi embedded",
     "domanda": "Hai competenze nello sviluppo di applicazioni per dispositivi embedded?"},
    {"categoria": "competenze", "testo": "Ottimizzazione delle prestazioni del software",
     "domanda": "Sai ottimizzare le prestazioni del software?"},
    {"categoria": "competenze", "testo": "Sviluppo di moduli aggiuntivi per software",
     "domanda": "Hai esperienza nello sviluppo di moduli aggiuntivi per software?"},
    {"categoria": "competenze", "testo": "Creazione di algoritmi di apprendimento automatico",
     "domanda": "Sai creare algoritmi di apprendimento automatico?"},
    {"categoria": "competenze", "testo": "Automazione dei processi di business",
     "domanda": "Hai esperienza nell'automazione dei processi di business?"},
    {"categoria": "competenze", "testo": "Sviluppo di applicazioni per reti neurali artificiali",
     "domanda": "Hai competenze nello sviluppo di applicazioni per reti neurali artificiali?"},
    {"categoria": "competenze", "testo": "Analisi di grandi quantità di dati",
     "domanda": "Sai analizzare grandi quantità di dati?"},
    {"categoria": "competenze", "testo": "Gestione di piattaforme di e-commerce",
     "domanda": "Hai esperienza nella gestione di piattaforme di e-commerce?"},
    {"categoria": "competenze", "testo": "Risoluzione dei problemi di sicurezza informatica",
     "domanda": "Sai risolvere i problemi di sicurezza informatica?"},
    {"categoria": "competenze", "testo": "Ricerca e sviluppo di algoritmi di crittografia",
     "domanda": "Hai esperienza nella ricerca e sviluppo di algoritmi di crittografia?"},
    {"categoria": "competenze", "testo": "Sviluppo di algoritmi di intelligenza artificiale",
     "domanda": "Sai sviluppare algoritmi di intelligenza artificiale?"},


    {"categoria": "esperienze", "testo": "Direttore dei Sistemi Informativi",
     "domanda": "Hai esperienza come direttore dei Sistemi Informativi?"},
    {"categoria": "competenze", "testo": "sviluppo di applicazioni",
     "domanda": "Hai esperienza in sviluppo di applicazioni?"},
    {"categoria": "competenze", "testo": "gestione di progetti open-source",
     "domanda": "Hai esperienza in gestione di progetti open-source?"},
    {"categoria": "esperienze", "testo": "Programmatore Software",
     "domanda": "Hai esperienza come Programmatore Software?"},
    {"categoria": "competenze", "testo": "Analisi dei dati aziendali",
     "domanda": "Hai esperienza nell'analisi dei dati aziendali?"},
    {"categoria": "competenze", "testo": "Sviluppo di software su misura",
     "domanda": "Hai esperienza nello sviluppo di software su misura?"},
    {"categoria": "competenze", "testo": "Migrazione di sistemi IT",
     "domanda": "Hai esperienza nella migrazione di sistemi IT?"},
    {"categoria": "competenze", "testo": "Formazione di personale tecnico",
     "domanda": "Hai esperienza nella formazione di personale tecnico?"},
    {"categoria": "competenze", "testo": "Integrazione di sistemi",
     "domanda": "Hai esperienza nell'integrazione di sistemi?"},
    {"categoria": "competenze", "testo": "Risoluzione di problemi hardware e software",
     "domanda": "Hai esperienza nella risoluzione di problemi hardware e software?"},
    {"categoria": "competenze", "testo": "Gestione di infrastrutture IT",
     "domanda": "Hai esperienza nella gestione di infrastrutture IT?"},
    {"categoria": "esperienze", "testo": "Collaborazione con clienti per definire requisiti",
     "domanda": "Hai esperienza nella collaborazione con clienti per definire requisiti?"},
    {"categoria": "esperienze", "testo": "Partecipazione a team di sviluppo Agile",
     "domanda": "Hai esperienza nella partecipazione a team di sviluppo Agile?"},
    {"categoria": "competenze", "testo": "Test di sicurezza informatica",
     "domanda": "Hai esperienza nel test di sicurezza informatica?"},
    {"categoria": "competenze", "testo": "Gestione di piattaforme cloud",
     "domanda": "Hai esperienza nella gestione di piattaforme cloud?"},
    {"categoria": "esperienze", "testo": "Collaborazione con team di ricerca e sviluppo",
     "domanda": "Hai esperienza nella collaborazione con team di ricerca e sviluppo?"},
    {"categoria": "competenze", "testo": "Utilizzo di metodologie DevOps",
     "domanda": "Hai esperienza nell'utilizzo di metodologie DevOps?"},
    {"categoria": "competenze", "testo": "Implementazione di sistemi ERP",
     "domanda": "Hai esperienza nell'implementazione di sistemi ERP?"},
    {"categoria": "competenze", "testo": "Gestione di servizi IT",
     "domanda": "Hai esperienza nella gestione di servizi IT?"},
    {"categoria": "competenze", "testo": "Sviluppo di interfacce utente intuitive",
     "domanda": "Hai esperienza nello sviluppo di interfacce utente intuitive?"},
    {"categoria": "competenze", "testo": "Automazione di processi aziendali",
     "domanda": "Hai esperienza nell'automazione di processi aziendali?"},
    {"categoria": "competenze", "testo": "Ricerca e implementazione di nuove tecnologie",
     "domanda": "Hai esperienza nella ricerca e implementazione di nuove tecnologie?"},
    {"categoria": "competenze", "testo": "Gestione di team di sviluppo software",
     "domanda": "Hai esperienza nella gestione di team di sviluppo software?"},
    {"categoria": "competenze", "testo": "Progettazione di architetture IT",
     "domanda": "Hai esperienza nella progettazione di architetture IT?"},
    {"categoria": "competenze", "testo": "Analisi e miglioramento delle performance dei sistemi",
     "domanda": "Hai esperienza nell'analisi e miglioramento delle performance dei sistemi?"},
    {"categoria": "competenze", "testo": "Sviluppo e manutenzione di sistemi di gestione della conoscenza",
     "domanda": "Hai esperienza nello sviluppo e manutenzione di sistemi di gestione della conoscenza?"},
    {"categoria": "competenze", "testo": "Collaborazione con team multidisciplinari",
     "domanda": "Hai esperienza nella collaborazione con team multidisciplinari?"},
    {"categoria": "competenze", "testo": "Gestione di processi di qualità del software",
     "domanda": "Hai esperienza nella gestione di processi di qualità del software?"},
    {"categoria": "competenze", "testo": "Sviluppo di applicazioni distribuite",
     "domanda": "Hai esperienza nello sviluppo di applicazioni distribuite?"},
    {"categoria": "competenze", "testo": "Monitoraggio e ottimizzazione delle performance delle applicazioni",
     "domanda": "Hai esperienza nel monitoraggio e ottimizzazione delle performance delle applicazioni?"},
    {"categoria": "competenze", "testo": "Gestione di progetti di migrazione dati",
     "domanda": "Hai esperienza nella gestione di progetti di migrazione dati?"},
    {"categoria": "competenze", "testo": "Collaborazione con team di supporto tecnico",
     "domanda": "Hai esperienza nella collaborazione con team di supporto tecnico?"},
    {"categoria": "competenze", "testo": "Sviluppo di sistemi embedded",
     "domanda": "Hai esperienza nello sviluppo di sistemi embedded?"},
    {"categoria": "competenze", "testo": "Gestione di infrastrutture di rete",
     "domanda": "Hai esperienza nella gestione di infrastrutture di rete?"},
    {"categoria": "competenze", "testo": "Collaborazione con team di cybersecurity",
     "domanda": "Hai esperienza nella collaborazione con team di cybersecurity?"},
    {"categoria": "competenze", "testo": "Progettazione e implementazione di soluzioni di business intelligence",
     "domanda": "Hai esperienza nella progettazione e implementazione di soluzioni di business intelligence?"},
    {"categoria": "esperienze", "testo": "Programmatore Software",
     "domanda": "Hai esperienza come Programmatore Software?"},
    {"categoria": "esperienze", "testo": "Direttore dei Sistemi Informativi",
     "domanda": "Hai esperienza come direttore dei Sistemi Informativi?"},
    {"categoria": "competenze", "testo": "Sviluppo di applicazioni",
     "domanda": "Hai esperienza nello sviluppo di applicazioni?"},
    {"categoria": "competenze", "testo": "Gestione di progetti open-source",
     "domanda": "Hai esperienza nella gestione di progetti open-source?"},
    {"categoria": "esperienze", "testo": "Programmatore Software",
     "domanda": "Hai esperienza come Programmatore Software?"},
    {"categoria": "competenze", "testo": "Analisi dei requisiti software",
     "domanda": "Hai esperienza nell'analisi dei requisiti software?"},
    {"categoria": "esperienze", "testo": "Sviluppatore di software per piattaforme web",
     "domanda": "Hai esperienza nello sviluppo di software per piattaforme web?"},
    {"categoria": "competenze", "testo": "Gestione di team di sviluppo software",
     "domanda": "Hai esperienza nella gestione di team di sviluppo software?"},
    {"categoria": "competenze", "testo": "Implementazione di sistemi di gestione di database",
     "domanda": "Hai esperienza nell'implementazione di sistemi di gestione di database?"},
    {"categoria": "competenze", "testo": "Progettazione e sviluppo di software per dispositivi mobili",
     "domanda": "Hai esperienza nella progettazione e sviluppo di software per dispositivi mobili?"},
    {"categoria": "competenze", "testo": "Collaborazione con team di testing software",
     "domanda": "Hai esperienza nella collaborazione con team di testing software?"},
    {"categoria": "competenze", "testo": "Partecipazione a progetti di sviluppo Agile",
     "domanda": "Hai esperienza nella partecipazione a progetti di sviluppo Agile?"},
    {"categoria": "competenze", "testo": "Gestione di piattaforme e-commerce",
     "domanda": "Hai esperienza nella gestione di piattaforme e-commerce?"},
    {"categoria": "competenze", "testo": "Manutenzione e aggiornamento di software esistenti",
     "domanda": "Hai esperienza nella manutenzione e aggiornamento di software esistenti?"},
    {"categoria": "competenze", "testo": "Sviluppo di applicazioni desktop",
     "domanda": "Hai esperienza nello sviluppo di applicazioni desktop?"},
    {"categoria": "competenze", "testo": "Collaborazione con team di UX/UI design",
     "domanda": "Hai esperienza nella collaborazione con team di UX/UI design?"},
    {"categoria": "competenze", "testo": "Utilizzo di metodologie di sviluppo software lean",
     "domanda": "Hai esperienza nell'utilizzo di metodologie di sviluppo software lean?"},
    {"categoria": "competenze", "testo": "Automazione di processi di sviluppo software",
     "domanda": "Hai esperienza nell'automazione di processi di sviluppo software?"},
    {"categoria": "competenze", "testo": "Gestione di sistemi di versioning software",
     "domanda": "Hai esperienza nella gestione di sistemi di versioning software?"},
    {"categoria": "esperienze", "testo": "Analista di Sistemi", "domanda": "Hai esperienza come Analista di Sistemi?"},
    {"categoria": "esperienze", "testo": "Ingegnere del Software",
     "domanda": "Hai esperienza come Ingegnere del Software?"},
    {"categoria": "esperienze", "testo": "Specialista in Sicurezza Informatica",
     "domanda": "Hai esperienza come Specialista in Sicurezza Informatica?"},
    {"categoria": "esperienze", "testo": "Sviluppatore Web", "domanda": "Hai esperienza come Sviluppatore Web?"},
    {"categoria": "esperienze", "testo": "Amministratore di Rete",
     "domanda": "Hai esperienza come Amministratore di Rete?"},
    {"categoria": "esperienze", "testo": "Analista di Dati", "domanda": "Hai esperienza come Analista di Dati?"},
    {"categoria": "esperienze", "testo": "Gestore dei Progetti IT",
     "domanda": "Hai esperienza come Gestore dei Progetti IT?"},
    {"categoria": "esperienze", "testo": "Architetto delle Soluzioni",
     "domanda": "Hai esperienza come Architetto delle Soluzioni?"},
    {"categoria": "esperienze", "testo": "Programmatore di Applicazioni Mobili",
     "domanda": "Hai esperienza come Programmatore di Applicazioni Mobili?"},
    {"categoria": "esperienze", "testo": "Tecnico di Supporto IT",
     "domanda": "Hai esperienza come Tecnico di Supporto IT?"},
    {"categoria": "esperienze", "testo": "Esperto di Business Intelligence",
     "domanda": "Hai esperienza come Esperto di Business Intelligence?"},
    {"categoria": "esperienze", "testo": "Responsabile della Qualità del Software",
     "domanda": "Hai esperienza come Responsabile della Qualità del Software?"},
    {"categoria": "esperienze", "testo": "Sviluppatore di Applicazioni Desktop",
     "domanda": "Hai esperienza come Sviluppatore di Applicazioni Desktop?"},
    {"categoria": "esperienze", "testo": "Consulente IT", "domanda": "Hai esperienza come Consulente IT?"},
    {"categoria": "esperienze", "testo": "Gestore dei Sistemi di Database",
     "domanda": "Hai esperienza come Gestore dei Sistemi di Database?"},
    {"categoria": "esperienze", "testo": "Esperto di Reti", "domanda": "Hai esperienza come Esperto di Reti?"},
    {"categoria": "esperienze", "testo": "Analista di Sicurezza Informatica",
     "domanda": "Hai esperienza come Analista di Sicurezza Informatica?"},
    {"categoria": "esperienze", "testo": "Consulente in Tecnologie dell'Informazione",
     "domanda": "Hai esperienza come Consulente in Tecnologie dell'Informazione?"},
    {"categoria": "esperienze", "testo": "Data scientist",
     "domanda": "Hai esperienza come Data scientist?"},
    {"categoria": "titoli_di_studio", "testo": "Percorso di studi ad indirizzo tecnico/informatico",
     "domanda": "Hai seguito un percorso di studi ad indirizzo tecnico/informatico?"},
]


import torch
from transformers import T5Tokenizer, T5ForConditionalGeneration
from torch.utils.data import Dataset, DataLoader

class QuestionGenerationDataset(Dataset):
    def __init__(self, dataset):
        self.dataset = dataset
        self.tokenizer = T5Tokenizer.from_pretrained('t5-small')

    def __len__(self):
        return len(self.dataset)

    def __getitem__(self, idx):
        data_point = self.dataset[idx]
        return data_point['testo'], data_point['categoria'], data_point['domanda']

    def collate_fn(self, batch):
        texts, categories, questions = zip(*batch)
        inputs = self.tokenizer(texts, return_tensors='pt', padding=True, truncation=True)
        labels = self.tokenizer(questions, return_tensors='pt', padding=True, truncation=True)
        inputs['labels'] = labels['input_ids']
        inputs['categories'] = categories  # Aggiungi le categorie al batch
        return inputs


from transformers import T5ForConditionalGeneration

class T5WithCategories(T5ForConditionalGeneration):
    def forward(
        self,
        input_ids=None,
        attention_mask=None,
        decoder_input_ids=None,
        decoder_attention_mask=None,
        head_mask=None,
        decoder_head_mask=None,
        encoder_outputs=None,
        past_key_values=None,
        inputs_embeds=None,
        decoder_inputs_embeds=None,
        labels=None,
        use_cache=None,
        output_attentions=None,
        output_hidden_states=None,
        return_dict=None,
        categories=None,  # Aggiungi il parametro delle categorie
        cross_attn_head_mask = None  # Aggiungi il parametro cross_attn_head_mask
    ):
        # Aggiungi la gestione delle categorie al passaggio in avanti
        outputs = super().forward(
            input_ids=input_ids,
            attention_mask=attention_mask,
            decoder_input_ids=decoder_input_ids,
            decoder_attention_mask=decoder_attention_mask,
            head_mask=head_mask,
            decoder_head_mask=decoder_head_mask,
            encoder_outputs=encoder_outputs,
            past_key_values=past_key_values,
            inputs_embeds=inputs_embeds,
            decoder_inputs_embeds=decoder_inputs_embeds,
            labels=labels,
            use_cache=use_cache,
            output_attentions=output_attentions,
            output_hidden_states=output_hidden_states,
            return_dict=return_dict,
            cross_attn_head_mask=cross_attn_head_mask  # Passa cross_attn_head_mask
        )

        return outputs


# Creazione del dataset e dataloader
question_dataset = QuestionGenerationDataset(dataset)
dataloader = DataLoader(question_dataset, batch_size=2, collate_fn=question_dataset.collate_fn)

#model_path = "C:/Users/termi/PycharmProjects/skillCheck/modelli/questioner"
#model = T5WithCategories.from_pretrained(model_path)

# Inizializzazione del modello
model = T5WithCategories.from_pretrained('t5-small')
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device)

# Addestramento
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-4)
epochs = 40

for epoch in range(epochs):
    print(f"Epoch {epoch + 1}/{epochs}")
    model.train()
    total_loss = 0

    for batch_idx, batch in enumerate(dataloader):
        inputs = {
            'input_ids': batch['input_ids'].to(device),
            'attention_mask': batch['attention_mask'].to(device),
            'labels': batch['labels'].to(device),
            'categories': batch['categories']  # Passa le categorie al modello
        }
        optimizer.zero_grad()
        outputs = model(**inputs)
        loss = outputs.loss
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

        # Stampa di controllo degli output
        if (batch_idx + 1) % 10 == 0:
            print(f"Iteration: {batch_idx + 1}/{len(dataloader)}, Loss: {loss.item()}")

# Salva il modello addestrato
output_dir = "C:/Users/termi/PycharmProjects/skillCheck/modelli/questioner"
model.save_pretrained(output_dir)
