# Generated by Django 4.2.7 on 2023-11-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='matched_similarity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
