# Generated by Django 4.2.7 on 2023-12-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0002_resume_matched_similarity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='matched_similarity',
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='competence_features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='nice_to_have_features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='competence_similarity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='degree',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='nice_to_have_similarity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
