# Generated by Django 4.2.7 on 2023-12-28 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0003_remove_resume_matched_similarity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdescription',
            old_name='position',
            new_name='degree',
        ),
    ]
