# Generated by Django 4.2.7 on 2024-01-28 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0004_rename_position_jobdescription_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdescription',
            name='competence_features',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='nice_to_have_features',
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='competence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='nice_to_have',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_description',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='skillApp.jobdescription'),
        ),
    ]
