# Generated by Django 4.2.7 on 2024-01-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0005_remove_jobdescription_competence_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdescription',
            name='competence',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='nice_to_have',
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='parameters',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
