# Generated by Django 4.2.7 on 2024-01-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0006_remove_jobdescription_competence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='degree',
        ),
        migrations.AddField(
            model_name='resume',
            name='degree_similarity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='pdf_file',
            field=models.BinaryField(),
        ),
    ]
