# Generated by Django 4.2.7 on 2024-01-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0007_remove_resume_degree_resume_degree_similarity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='pdf_file',
            field=models.FileField(upload_to=''),
        ),
    ]
