# Generated by Django 4.2.7 on 2024-01-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0008_alter_resume_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='pdf_file',
            field=models.FileField(upload_to='pdf_resumes/'),
        ),
    ]
