# Generated by Django 4.2.7 on 2024-01-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0009_resume_resume_text_alter_resume_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='pdf_file',
            field=models.BinaryField(),
        ),
    ]
