# Generated by Django 4.2.7 on 2024-01-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0010_alter_resume_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='pdf_file_upload',
            field=models.FileField(blank=True, null=True, upload_to='pdf_resumes/'),
        ),
    ]
