# Generated by Django 4.2.7 on 2024-03-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0011_resume_pdf_file_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdescription',
            name='parameters',
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='competenze',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='esperienze',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='titoli_di_studio',
            field=models.TextField(blank=True),
        ),
    ]
