# Generated by Django 4.2.7 on 2024-03-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0012_remove_jobdescription_parameters_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='competence_similarity',
            new_name='competenze_similarity',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='nice_to_have_similarity',
            new_name='esperienze_similarity',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='degree_similarity',
            new_name='titoli_di_studio_similarity',
        ),
        migrations.AddField(
            model_name='resume',
            name='competenze',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='esperienze',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='titoli_di_studio',
            field=models.TextField(blank=True),
        ),
    ]
