# Generated by Django 4.2.7 on 2024-03-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0013_rename_competence_similarity_resume_competenze_similarity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='domande_competenze',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='domande_esperienze',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='domande_titoli_di_studio',
            field=models.TextField(blank=True),
        ),
    ]
