# Generated by Django 4.2.7 on 2024-03-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0014_jobdescription_domande_competenze_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='pdf_file',
            new_name='pdf_content',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='pdf_file_upload',
        ),
    ]
