# Generated by Django 4.2.7 on 2024-03-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0015_rename_pdf_file_resume_pdf_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='pdf_content',
            new_name='pdf_file',
        ),
        migrations.AddField(
            model_name='resume',
            name='pdf_file_upload',
            field=models.FileField(blank=True, null=True, upload_to='pdf_resumes/'),
        ),
    ]
