# Generated by Django 4.2.7 on 2024-03-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0016_rename_pdf_content_resume_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='resumes',
            field=models.ManyToManyField(related_name='job_descriptions', to='skillApp.resume'),
        ),
    ]
