# Generated by Django 4.2.7 on 2024-03-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0018_jobdescription_domande_selezionate'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='domande_affinity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
