# Generated by Django 4.2.7 on 2024-03-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0019_resume_domande_affinity'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='domande_selezionabili',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='domande_personali',
            field=models.TextField(blank=True),
        ),
    ]
