# Generated by Django 4.2.7 on 2024-03-30 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0020_jobdescription_domande_selezionabili_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdescription',
            old_name='domande_selezionabili',
            new_name='domande_con_data',
        ),
    ]
