# Generated by Django 4.2.7 on 2024-04-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0021_rename_domande_selezionabili_jobdescription_domande_con_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='domande_e_risposte',
            field=models.JSONField(default=dict),
        ),
    ]
