# Generated by Django 5.2.4 on 2026-04-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0022_resume_domande_e_risposte'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='risposte_personalita_raw',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
