# Generated by Django 5.2.4 on 2026-05-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0023_resume_risposte_personalita_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('tratto', models.CharField(max_length=1)),
                ('direzione', models.CharField(max_length=1)),
            ],
        ),
    ]
