# Generated by Django 5.2.4 on 2026-05-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0024_personalityquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='risposte_personalita_raw',
        ),
    ]
