# Generated by Django 5.2.4 on 2026-05-22 13:44

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0025_remove_resume_risposte_personalita_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='risposte_personalita_raw',
            field=django_cryptography.fields.encrypt(models.JSONField(blank=True, null=True)),
        ),
    ]
