# Generated by Django 5.2.4 on 2026-06-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0026_resume_risposte_personalita_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality_type', models.CharField(max_length=10, unique=True)),
                ('last_used_sequence', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality_type', models.CharField(max_length=10)),
                ('sequence_number', models.IntegerField()),
                ('body_text', models.TextField()),
            ],
            options={
                'unique_together': {('personality_type', 'sequence_number')},
            },
        ),
    ]
