# Generated by Django 5.2.4 on 2026-07-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0027_personalitycounter_emailtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalitycounter',
            name='personality_type',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
