# Generated by Django 4.2.7 on 2026-07-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0028_alter_personalitycounter_personality_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
