# Generated by Django 4.2.7 on 2026-08-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0029_resume_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
