# Generated by Django 4.2.7 on 2026-08-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0030_jobdescription_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('reparto', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
