# Generated by Django 4.2.7 on 2026-09-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0031_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='competenze',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='employee_cvs/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='esperienze',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='titoli_di_studio',
            field=models.TextField(blank=True),
        ),
    ]
