# Generated by Django 4.2.7 on 2026-09-28 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0032_employee_competenze_employee_cv_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeJobScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility', models.FloatField()),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_scores', to='skillApp.employee')),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_scores', to='skillApp.jobdescription')),
            ],
            options={
                'unique_together': {('employee', 'job_description')},
            },
        ),
    ]
