# Generated by Django 4.2.23 on 2025-09-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='job_code',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
